<a href="https://colab.research.google.com/github/sasansharee/Sasan_MMA/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [103]:
import numpy as np
import pandas as pd

In [104]:
# 1- Create three lists representing house features, each list containing ten values.
# The first one for the house's size in square meters, the second one for rooms and last for price.
#Then, create an array combining these lists.

house_size = [i for i in range(60, 160, 10)]
room_num = list(np.random.randint(1, 5, size =10))
house_price = list(np.random.randint(100000, 350000, size = 10))
combined_array = np.array([house_size, room_num, house_price])
combined_array

array([[    60,     70,     80,     90,    100,    110,    120,    130,
           140,    150],
       [     4,      2,      1,      2,      1,      4,      1,      1,
             2,      1],
       [153892, 237849, 287886, 172356, 213405, 116805, 162570, 100012,
        337788, 137571]])

In [105]:
# 2- Transpose the array you have created, so that every line can represent features of one house.
combined_array.transpose()

array([[    60,      4, 153892],
       [    70,      2, 237849],
       [    80,      1, 287886],
       [    90,      2, 172356],
       [   100,      1, 213405],
       [   110,      4, 116805],
       [   120,      1, 162570],
       [   130,      1, 100012],
       [   140,      2, 337788],
       [   150,      1, 137571]])

In [106]:
# 3- Display the shape of the array and explain what it means.
combined_array.shape # It is a 2 dimesnioan matrix with 3 rows and 10 columns

(3, 10)

In [107]:
# 4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.
Eq = pd.read_csv('/content/earthquakes1970-2014.csv')
Eq_arr =Eq.to_numpy()
Eq_arr

array([['1970/01/04 17:00:40.20', 24.1389999999999, 102.503, ..., 0.0,
        'NEI', 1970010440.0],
       ['1970/01/06 05:35:51.80', -9.628, 151.458, ..., 0.0, 'NEI',
        1970010640.0],
       ['1970/01/08 17:12:39.10', -34.741, 178.568, ..., 0.0, 'NEI',
        1970010840.0],
       ...,
       ['2013/12/17 23:38:08.10', 20.7635, 146.759899999999, ..., 0.74,
        'us', 2013121720.0],
       ['2014/01/01 16:03:28.89', -13.8779, 167.2434, ..., 0.67, 'us',
        2014010120.0],
       ['2014/01/13 04:01:04.69', 19.0014, -66.8478, ..., 1.42, 'us',
        2014011320.0]], dtype=object)

In [108]:
# 5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.
Slice_1 = Eq_arr[0:20, [2, 4, 5, 6, 11]]

In [109]:
# 6- Display the row numbers where last values are equal to 4.5 or higher.
row_index = [i for i in range(len(Slice_1)) if Slice_1[i, -1] >= 4.5]
row_index

[0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 19]

In [110]:
# 7- Assign 1 to first row.
Slice_2 = Slice_1[row_index, :]
Slice_2[0] = 1
Slice_2

array([[1, 1, 1, 1, 1],
       [151.458, 6.2, 'Ms', 85.0, 1970010640.0],
       [178.568, 6.1, 'Mb', 59.0, 1970010840.0],
       [126.736999999999, 6.1, 'Mb', 91.0, 1970011040.0],
       [-177.348999999999, 6.5, 'Mb', 175.0, 1970012040.0],
       [142.966, 6.4, 'Ms', 199.0, 1970012040.0],
       [-104.298, 6.6, 'Ms', 140.0, 1970012140.0],
       [166.37, 6.4, 'Ms', 91.0, 1970012640.0],
       [-99.48399999999991, 6.5, 'Ms', 100.0, 1970020440.0],
       [122.117, 6.6, 'Ms', 94.0, 1970020540.0],
       [100.775, 6.1, 'Ms', 57.0, 1970020640.0],
       [103.031, 6.0, 'Ms', 94.0, 1970022440.0],
       [143.706999999999, 6.2, 'Ms', 82.0, 1970030440.0],
       [168.603, 6.5, 'Ms', 61.0, 1970030940.0],
       [148.87, 6.0, 'Mb', 65.0, 1970031040.0],
       [-69.49899999999991, 6.0, 'Mb', 118.0, 1970031540.0]], dtype=object)

In [111]:
# 8- Save the final state of the array to disk. You are going to use this in the next assignment.
np.save('Slice_2.npy', Slice_2)

In [112]:
# 9- Load the array you saved in the previous lesson from the disk.
loaded_array = np.load('Slice_2.npy', allow_pickle=True)
display(loaded_array)

array([[1, 1, 1, 1, 1],
       [151.458, 6.2, 'Ms', 85.0, 1970010640.0],
       [178.568, 6.1, 'Mb', 59.0, 1970010840.0],
       [126.736999999999, 6.1, 'Mb', 91.0, 1970011040.0],
       [-177.348999999999, 6.5, 'Mb', 175.0, 1970012040.0],
       [142.966, 6.4, 'Ms', 199.0, 1970012040.0],
       [-104.298, 6.6, 'Ms', 140.0, 1970012140.0],
       [166.37, 6.4, 'Ms', 91.0, 1970012640.0],
       [-99.48399999999991, 6.5, 'Ms', 100.0, 1970020440.0],
       [122.117, 6.6, 'Ms', 94.0, 1970020540.0],
       [100.775, 6.1, 'Ms', 57.0, 1970020640.0],
       [103.031, 6.0, 'Ms', 94.0, 1970022440.0],
       [143.706999999999, 6.2, 'Ms', 82.0, 1970030440.0],
       [168.603, 6.5, 'Ms', 61.0, 1970030940.0],
       [148.87, 6.0, 'Mb', 65.0, 1970031040.0],
       [-69.49899999999991, 6.0, 'Mb', 118.0, 1970031540.0]], dtype=object)

In [138]:
# 10- Display the mean and the standard deviation for each column.
def is_numerical(col):
  try:
    col.astype(float)
    return True
  except ValueError:
    return False

numerical_columns = [i for i in range(loaded_array.shape[1]) if is_numerical(loaded_array[:,i])]
print(numerical_columns)

column_mean = np.mean(loaded_array[:, numerical_columns], axis = 0)
print(column_mean)

column_std = (np.var(loaded_array[:, numerical_columns], axis = 0)) ** 0.5
print(column_std)



[0, 1, 3, 4]
[68.97324999999995 5.95 94.5 1846893087.5625]
[113.70824718852829 1.295665851984994 45.91159984143441 476865744.4962063]


In [134]:
def is_numerical(column):
  try:
    column.astype(float)
    return True
  except ValueError:
    return False

numerical_columns = [i for i in range(loaded_array.shape[1]) if is_numerical(loaded_array[:, i])]

column_mean = []
for i in numerical_columns:
  column_mean.append(loaded_array[:, i].mean())
  print(f'The mean of column {i} is {column_mean[-1]} ')

column_std = []
for i in numerical_columns:
  column_std.append(loaded_array[:, i].std())
  print(f'The std of column {i} is {column_std[-1]} ')


The mean of column 0 is 68.97324999999995 
The mean of column 1 is 5.95 
The mean of column 3 is 94.5 
The mean of column 4 is 1846893087.5625 
The std of column 0 is 113.70824718852829 
The std of column 1 is 1.295665851984994 
The std of column 3 is 45.91159984143441 
The std of column 4 is 476865744.4962063 


In [148]:
# 11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)
loaded_array[:, numerical_columns] - [1, 25, 10, 4]

array([[0, -24, -9, -3],
       [150.458, -18.8, 75.0, 1970010636.0],
       [177.568, -18.9, 49.0, 1970010836.0],
       [125.736999999999, -18.9, 81.0, 1970011036.0],
       [-178.348999999999, -18.5, 165.0, 1970012036.0],
       [141.966, -18.6, 189.0, 1970012036.0],
       [-105.298, -18.4, 130.0, 1970012136.0],
       [165.37, -18.6, 81.0, 1970012636.0],
       [-100.48399999999991, -18.5, 90.0, 1970020436.0],
       [121.117, -18.4, 84.0, 1970020536.0],
       [99.775, -18.9, 47.0, 1970020636.0],
       [102.031, -19.0, 84.0, 1970022436.0],
       [142.706999999999, -18.8, 72.0, 1970030436.0],
       [167.603, -18.5, 51.0, 1970030936.0],
       [147.87, -19.0, 55.0, 1970031036.0],
       [-70.49899999999991, -19.0, 108.0, 1970031536.0]], dtype=object)

In [150]:
# 12- Multiply each element by 2. (Remember it can be done in one line of code.)
loaded_array * 2

array([[2, 2, 2, 2, 2],
       [302.916, 12.4, 'MsMs', 170.0, 3940021280.0],
       [357.136, 12.2, 'MbMb', 118.0, 3940021680.0],
       [253.473999999998, 12.2, 'MbMb', 182.0, 3940022080.0],
       [-354.697999999998, 13.0, 'MbMb', 350.0, 3940024080.0],
       [285.932, 12.8, 'MsMs', 398.0, 3940024080.0],
       [-208.596, 13.2, 'MsMs', 280.0, 3940024280.0],
       [332.74, 12.8, 'MsMs', 182.0, 3940025280.0],
       [-198.96799999999982, 13.0, 'MsMs', 200.0, 3940040880.0],
       [244.234, 13.2, 'MsMs', 188.0, 3940041080.0],
       [201.55, 12.2, 'MsMs', 114.0, 3940041280.0],
       [206.062, 12.0, 'MsMs', 188.0, 3940044880.0],
       [287.413999999998, 12.4, 'MsMs', 164.0, 3940060880.0],
       [337.206, 13.0, 'MsMs', 122.0, 3940061880.0],
       [297.74, 12.0, 'MbMb', 130.0, 3940062080.0],
       [-138.99799999999982, 12.0, 'MbMb', 236.0, 3940063080.0]],
      dtype=object)